---
title: "Plume generation in natural thermal convection at high Rayleigh and Prandtl numbers"
date: 2001-01-01
publishDate: 2020-07-16T00:16:52.044293Z
authors: ["Carolina Lithgow-Bertelloni", "Mark A. Richards", "Clinton P. Conrad", "Ross W. Griffiths"]
publication_types: ["2"]
abstract: "We study natural thermal convection of a fluid (corn syrup) with a large Prandtl number (10(3)-10(7)) and temperature-dependent viscosity. The experimental tank (1 x 1 x 0.3 m) is heated from below with insulating top and side boundaries, so that the fluid experiences secular heating as experiments proceed. This setup allows a focused study of thermal plumes from the bottom boundary layer over a range of Rayleigh numbers relevant to convective plumes in the deep interior of the Earth's mantle. The effective value of Ra, based on the viscosity of the fluid at the interior temperature, varies from 10(5) at the beginning to almost 10(8) toward the end of the experiments. Thermals (plumes) from the lower boundary layer are trailed by continuous conduits with long residence times. Plumes dominate flow in the tank, although there is a weaker large-scale circulation induced by material cooling at the imperfectly insulating top and sidewalls. At large Ra convection is extremely time-dependent and exhibits episodic bursts of plumes, separated by periods of quiescence. This bursting behaviour probably results from the inability of the structure of the thermal boundary layer and its instabilities to keep pace with the rate of secular change in the value of Ra. The frequency of plumes increases and their size decreases with increasing Ra, and we characterize these changes via in situ thermocouple measurements, shadowgraph videos, and videos of liquid crystal films recorded during several experiments. A scaling analysis predicts observed changes in plume head and tail radii with increasing Ra. Since inertial effects are largely absent no transition to 'hard' thermal turbulence is observed, in contrast to a previous conclusion from numerical calculations at similar Rayleigh numbers. We suggest that bursting behaviour similar to that observed may occur in the Earth's mantle as it undergoes secular cooling on the billion-year time scale."
featured: false
publication: "*J. Fluid Mechanics*"
---

