---
title: "An explanation for Earth's long-term rotational stability"
date: 1997-01-01
publishDate: 2020-07-16T00:16:52.047291Z
authors: ["Mark A. Richards", "Yanick Ricard", "Carolina Lithgow-Bertelloni", "Giorgio Spada", "Roberto Sabadini"]
publication_types: ["2"]
abstract: "Paleomagnetic data show less than similar to 1000 kilometers of motion between the paleomagnetic and hotspot reference frames-that is, true polar wander-during the past 100 million years, which implies that Earth's rotation axis has been very stable. This long-term rotational stability can be explained by the slow rate ol change in the large-scale pattern of plate tectonic motions during Cenozoic and late Mesozoic time, provided that subducted lithosphere is a major component of the mantle density heterogeneity generated by convection. Therefore, it is unnecessary to invoke other mechanisms, such as sluggish readjustment of the rotational bulge, to explain the observed low rate of true polar wander."
featured: false
publication: "*Science*"
---

