---
title: "Exhumation of a collisional orogen: A perspective from the North American Grenville Province"
date: 2004-01-01
publishDate: 2020-07-16T00:16:52.043148Z
authors: ["Margaret M. Streepey", "Carolina Lithgow-Bertelloni", "Ben A. van der Pluijm", "Eric J. Essene", "Jerry F. Magloughlin"]
publication_types: ["2"]
abstract: "Combined structural and geochronologic research in the southernmost portion of the contiguous Grenville Province of North America ( Ontario and New York State) show protracted periods of extension after the last episode of contraction. The Grenville Province in this area is characterized by synorogenic extension at ca. 1040 Ma, supported by U-Pb data on titanites and Ar-40-Ar-39 data on hornblendes, followed by regional extension occurring along crustal-scale shear zones between 945 and 780 Ma, as recorded by Ar-40-Ar-39 analysis of hornblende, biotite, and K-feldspar. By ca. 780 Ma the southern portion of the Grenville Province, from Ontario to the Adirondack Highlands, underwent uplift as a uniform block. Tectonic hypotheses have invoked various driving mechanisms to explain the transition from compression to extension; however, such explanations are thus far geodynamically unconstrained. Numerical models indicate that mechanisms such as gravitational collapse and mantle delamination act over timescales that cannot explain a protracted 300 m.y. extensional history that is contemporaneous with ongoing uplift of the Grenville Province. Rather, the presence of a plume upwelling underneath the Laurentian margin, combined with changes in regional stress directions, permitted the observed uplift and extension in the Grenville Province during this time. The uplift history, while on a slightly different timescale from those of most plume models, is similar to that seen in models of uplift and extension caused by the interaction of a plume with the base of the lithosphere. Some of the protracted extension likely reflects the contribution of far-field effects, possibly caused by tectonic activity in other cratons within the Rodinian supercontinent, effectively changing the stress distributions in the Grenville Province of northeastern North America."
featured: false
publication: "*Proterozoic Tectonic Evolution Grenville Orogen In North Am.*"
---

