---
title: "Global reconstructions of Cenozoic seafloor ages: Implications for bathymetry and sea level"
date: 2006-01-01
publishDate: 2020-07-16T00:16:52.032990Z
authors: ["Xiqiao Xu", "Carolina Lithgow-Bertelloni", "Clinton P. Conrad"]
publication_types: ["2"]
abstract: "Although accurate estimates of Cenozoic seafloor ages will serve to further our understanding of the relationship between mantle dynamics, plate tectonics, and a variety of surficial geological processes, it is difficult to estimate ages of subducted seafloor. However, given the near-constancy of surface velocities within a tectonic stage, we can estimate Cenozoic plate ages, even for subducted lithosphere. We reconstruct seafloor ages based on the Cenozoic plate reconstructions and absolute rotation poles of Gordon and Jurdy [R.G. Gordon and D.M. Jurdy, Cenozoic Global Plate Motions, J. Geophys. Res. 91 (1986) 12389-12406.]. For the western Pacific, we explore alternative models based on the reconstructions of Hall [R. Hall, Cenozoic geological and plate tectonic evolution of SE Asia and the SW Pacific: computer-based reconstructions, model and animations, J. Asian Earth Sci. 20 (2002) 353434.]. Both reconstructions indicate an increase in average seafloor age since the early Cenozoic, resulting in an increase in the volume of ocean basins and a decreased sea level since the Early Cenozoic. These trends are more pronounced for the Gordon and Jurdy [R.G. Gordon and D.M. Jurdy, Cenozoic Global Plate Motions, J. Geophys. Res. 91 (1986) 12,389-12,406.] reconstruction because the Hall [R. Hall, Cenozoic geological and plate tectonic evolution of SE Asia and the SW Pacific: computer-based reconstructions, model and animations, J. Asian Earth Sci. 20 (2002) 353-434.1 reconstruction retains older seafloor in the western Pacific, which approximately halves the predicted sea level decrease since the early Cenozoic (250 vs. 125 in compared to geologic estimates of similar to 150 in). These changes in sea level occur despite decreases in oceanic lithosphere production rates of only about 20% in both models. Thus, the changing distribution of seafloor age has a larger effect on sea level than changes in spreading rates or ridge lengths. These reconstructions can also be used to estimate past heat flow, the volume of subducted buoyancy and changes in the bathymetry of the Cenozoic ocean basins. (c) 2006 Elsevier B.V. All rights reserved."
featured: false
publication: "*Earth Planetary Science Lett.*"
---

